node edimaps.js -dmp:aamdfr
node edimaps.js -dmp:aamdjt
node edimaps.js -dmp:ama830
node edimaps.js -dmp:api830
node edimaps.js -dmp:ben862
node edimaps.js -dmp:ddi862
node edimaps.js -dmp:dxt850
node edimaps.js -dmp:bob850
node edimaps.js -dmp:gan830
node edimaps.js -dmp:jat830
node edimaps.js -dmp:krmdfr
node edimaps.js -dmp:len830
node edimaps.js -dmp:nav862
node edimaps.js -dmp:nsa830
node edimaps.js -dmp:plx830
node edimaps.js -dmp:plx862
node edimaps.js -dmp:pol850
node edimaps.js -dmp:pol860
node edimaps.js -dmp:pol862
node edimaps.js -dmp:riv830
node edimaps.js -dmp:riv850
node edimaps.js -dmp:riv860
node edimaps.js -dmp:riv862
node edimaps.js -dmp:sch830
node edimaps.js -dmp:sum830
node edimaps.js -dmp:sum850
node edimaps.js -dmp:tes830
node edimaps.js -dmp:tes862
node edimaps.js -dmp:tya830
node edimaps.js -dmp:tya862
node edimaps.js -dmp:trc850
node edimaps.js -dmp:vwsdfr
node edimaps.js -dmp:yzk830
pause
