node edimaps.js -dmp:aamdfr
node edimaps.js -dmp:aamdjt
node edimaps.js -dmp:akb830
node edimaps.js -dmp:ama830
node edimaps.js -dmp:api830
node edimaps.js -dmp:amg830
node edimaps.js -dmp:arw850
node edimaps.js -dmp:ben862
node edimaps.js -dmp:bch830
node edimaps.js -dmp:cmpdfr
node edimaps.js -dmp:ctl862
node edimaps.js -dmp:cumdjt
node edimaps.js -dmp:dao830
node edimaps.js -dmp:dao850
node edimaps.js -dmp:ddi862
node edimaps.js -dmp:dxt850
node edimaps.js -dmp:dxa850
node edimaps.js -dmp:dgk850
node edimaps.js -dmp:dmxdfr
node edimaps.js -dmp:dmxdjt
node edimaps.js -dmp:dns830
node edimaps.js -dmp:bob850
node edimaps.js -dmp:fdy830
node edimaps.js -dmp:flx830
node edimaps.js -dmp:gan830
node edimaps.js -dmp:hag830
node edimaps.js -dmp:hag850
node edimaps.js -dmp:hdk830
node edimaps.js -dmp:hin850
node edimaps.js -dmp:hon862
node edimaps.js -dmp:jat830
node edimaps.js -dmp:jel850
node edimaps.js -dmp:krmdfr
node edimaps.js -dmp:ktxdfr
node edimaps.js -dmp:kaw830
node edimaps.js -dmp:kaw850
node edimaps.js -dmp:kaw860
node edimaps.js -dmp:kwj830
node edimaps.js -dmp:len830
node edimaps.js -dmp:lucdfr
node edimaps.js -dmp:lucdjt
node edimaps.js -dmp:lucorc
node edimaps.js -dmp:lucord
node edimaps.js -dmp:mdx862
node edimaps.js -dmp:mmy830
node edimaps.js -dmp:msr850
node edimaps.js -dmp:nav862
node edimaps.js -dmp:nvs850
node edimaps.js -dmp:nsa830
node edimaps.js -dmp:plx830
node edimaps.js -dmp:plx862
node edimaps.js -dmp:pol850
node edimaps.js -dmp:pol860
node edimaps.js -dmp:pol862
node edimaps.js -dmp:riv830
node edimaps.js -dmp:riv850
node edimaps.js -dmp:riv860
node edimaps.js -dmp:riv862
node edimaps.js -dmp:sch830
node edimaps.js -dmp:sew830
node edimaps.js -dmp:sum830
node edimaps.js -dmp:sum850
node edimaps.js -dmp:tes830
node edimaps.js -dmp:tes862
node edimaps.js -dmp:tya830
node edimaps.js -dmp:tya862
node edimaps.js -dmp:trc850
node edimaps.js -dmp:tredfr
node edimaps.js -dmp:vmk830
node edimaps.js -dmp:vwsdfr
node edimaps.js -dmp:yzk830
node edimaps.js -dmp:zfpdfr
node edimaps.js -dmp:zfpdjt
node edimaps.js -dmp:zfpord
pause
